version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/repo
    branches:
      only:
        - master

    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Save NPM Package Cache
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - deploy:
          name: Deploy to branch gh-pages with "gh-pages" tool
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            npm run build
            echo -n "dett.cc" > build/CNAME
            npm run deploy-ghpages